services:
  pgsql_db:
    image: postgres:latest
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol: